---
- name: Create GitHub Webhook Wireless
  community.general.github_webhook:
    repository: "{{ github_user }}/{{ wireless_github_repo_name }}"
    url: "{{ job_template_webhook_url }}"
    secret: "{{ job_template_webhook_token }}"
    events:
      - push
    user: "{{ github_user }}"
    token: "{{ github_token }}"
    content_type: json
    insecure_ssl: true
  tags: github

- name: Create GitHub Webhook Firewall
  community.general.github_webhook:
    repository: "{{ rhsummitdemo_firewall }}"
    url: "{{ job_template_webhook_url }}"
    secret: "{{ job_template_webhook_token }}"
    events:
      - push
    user: "{{ github_user }}"
    token: "{{ github_token }}"
    content_type: json
    insecure_ssl: true
  tags: github
  # no quiero ejecutar esto aun
  when: true == false
